const nodemailer = require('nodemailer')
const dotenv = require('dotenv').config()

const sendMail = (data) => {
    let transporter = nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 465,
        secure: true,
        logger: true,
        auth: {
            user: process.env.MAIL_USER,
            pass: process.env.MAIL_PASS,
        }
    })
    // set up email data below
    let mailOptions = {
        from: `Personal Site: ${data.name},  <${data.email}>`, //sender
        to: process.env.MY_ADDY, //list receivers
        subject: `Personal Site: ${data.name} contacted you!`,
        text: `${data.message} -- ${data.email}`
    }
    let ccOptions = {
        from: `Jose Stricklin, <${process.env.MY_ADDY}>`, //sender
        to: data.email, //list receivers
        subject: 'Thanks for reaching out!',
        text: `Hey ${data.name},

        I will get back to you as soon as I can - thank you again for reaching out!

        - Jose Stricklin

(This message has been autogenerated - feel free to reach me at ${process.env.MY_ADDY})`
    }
    transporter.sendMail(mailOptions, (error, info) => {
        if (error) {
            return console.log(error)
        }
        console.log('Message sent: %s', info.messageId)
    })
    transporter.sendMail(ccOptions, (error, info) => {
        if (error) {
            return console.log(error)
        }
        console.log('Message sent: %s', info.messageId)
    })
}

module.exports = {
    sendMail
};
